export default {
  students: [],
  user: {},
  courses: [],
  course: {},
  classList: [],
  deliverables: [],
  courseSettings: {},
  teams: [],
  labSections: [],
  labs: [],
  myActiveCourse: {},
  myCourses: [],
  admins: [],
  authStatus: "Unauthenticated",
}