export default {
  students: [],
  user: {},
  course: {},
  courses: [],
  classList: [],
  deliverables: [],
  courseSettings: {},
  teams: [],
  myTeams: {},
  labSections: [],
  labs: [],
  myActiveCourse: {},
  myCourses: [],
  admins: [],
  github: {},
  studentsWithoutTeam: [],
  studentsWithTeam: [],
  teamCreationStatus: "",
  authStatus: "Unauthenticated",
}